version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./appdata:/runlviv/public
  app:
    build: .
    volumes:
      - ./appdata:/runlviv/public
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
